packages:
  - libs/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - prisma
  - sharp
  - sqlite3
  - supabase
  - unrs-resolver
